version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./backend/app/json:/backend/app/json
    command: ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]

  cron:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - ./backend/app/json:/backend/app/json
    command: sh entrypoint.sh
