name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Copy files to EC2 instance
      run: |
        INSTANCE_IP=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID}} --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
        scp -o StrictHostKeyChecking=no -r . ubuntu@ec2-${INSTANCE_IP}.${{ secrets.AWS_REGION}}.compute.amazonaws.com:/home/ubuntu/

    - name: Run deployment script
      run: |
        INSTANCE_IP=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID}} --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-${INSTANCE_IP}.${{ secrets.AWS_REGION}}.compute.amazonaws.com 'bash -s' < /lunch-scrape/initiate.sh
